#!/usr/bin/env bash

COMMAND=$1
ARGS=${@:2}

# echo "COMMAND: $COMMAND"
# echo "ELSE: $ARGS"

# if [[ "$COMMAND" == "init" ]]; then
#   # run init here (init)
#   echo "N/A"
#   exit 0
# fi

if [[ "$COMMAND" == "woop" ]]; then
  woop $ARGS
  exit 0
fi

if [[ -z "$COMMAND" ]]; then
  # here is where we show the manual
  # man slit (we may also need to add a man entry :) )
  echo "woop is the only command right now. woop woop"
  exit 0
fi

# Print error if no command (route) found
RED='\033[0;31m'
NC='\033[0m' # No Color
printf "${RED}Sorry, cmd [$COMMAND] not found${NC}\n"
exit 1
