#!/usr/bin/env bash

COMMAND=$1
ARGS=${@:2}
echo "COMMAND: $COMMAND"
echo "ELSE: $ARGS"

if [[ "$COMMAND" == "init" ]]; then
  # run init here (init)
  echo "N/A"
fi


if [[ "$COMMAND" == "woop" ]]; then
  echo "woop woop"
fi
