#!/usr/bin/env bash

TEST_NUM=1
TEST_DIR="test-cases"
TEST_OUT_DIR="test-runs"
EXECUTABLE=$1
# assume test-cases already exists
# promp the user to input test cases

mkdir -p $TEST_OUT_DIR

# while test exists, incrememnt
CONTINUE_TESTING=1
while [[ $CONTINUE_TESTING -eq 1 ]]; do

  # test and compare
  echo ""
  echo "--------------------------"
  echo "RUNNING TEST NUMBER: $TEST_NUM"
  echo "--------------------------"
  echo ""

  # in,out,expected paths
  IN="$TEST_DIR/$TEST_NUM-in.txt"
  OUT="$TEST_OUT_DIR/$TEST_NUM-out.txt"
  EXPECTED="$TEST_DIR/$TEST_NUM-out.txt"

  # run hw and diff output with test case

  # allow multiple input types in future (stdin & cli args)
  $EXECUTABLE < $IN &> $OUT
  colordiff $OUT $EXPECTED -y --width=80

  # increment test
  TEST_NUM=$(($TEST_NUM + 1))

  # if another test exists, continue
  TEST_CHECK=$(ls "$TEST_DIR/$TEST_NUM-in.txt" 2> /dev/null)
  if [[ -z "$TEST_CHECK" ]]; then
    CONTINUE_TESTING=0
  fi
done
